CREATE TYPE "public"."Goal status" AS ENUM('active', 'done');

--> statement-breakpoint
CREATE TYPE "public"."Task effort" AS ENUM('low', 'med', 'high');

--> statement-breakpoint
CREATE TYPE "public"."Task priority" AS ENUM('low', 'med', 'high');

--> statement-breakpoint
CREATE TYPE "public"."Task status" AS ENUM(
	'todo',
	'in progress',
	'blocked',
	'completed',
	'not done'
);

--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY NOT NULL,
	"email" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);

--> statement-breakpoint
ALTER TABLE
	"users" ENABLE ROW LEVEL SECURITY;

--> statement-breakpoint
CREATE TABLE "goals" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"category" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"status" "Goal status" DEFAULT 'active' NOT NULL,
	"start_date" date,
	"end_date" date,
	CONSTRAINT "goals_category_check" CHECK (
		category = ANY (
			ARRAY ['Main'::text, 'Yearly'::text, 'Quarterly'::text, 'Monthly'::text, 'Weekly'::text, 'Daily'::text]
		)
	)
);

--> statement-breakpoint
ALTER TABLE
	"goals" ENABLE ROW LEVEL SECURITY;

--> statement-breakpoint
CREATE TABLE "energy_readings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"level" integer NOT NULL,
	"note" text,
	"timestamp" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "energy_readings_level_check" CHECK (
		(level >= 1)
		AND (level <= 10)
	)
);

--> statement-breakpoint
ALTER TABLE
	"energy_readings" ENABLE ROW LEVEL SECURITY;

--> statement-breakpoint
CREATE TABLE "tasks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"parent_id" uuid,
	"title" text NOT NULL,
	"description" text,
	"completed" boolean DEFAULT false,
	"order_index" integer DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"status" "Task status" DEFAULT 'todo',
	"effort" "Task effort",
	"group_id" uuid,
	"isTemplate" boolean DEFAULT false NOT NULL,
	"templateId" uuid,
	"priority" "Task priority",
	"assignee_id" uuid
);

--> statement-breakpoint
ALTER TABLE
	"tasks" ENABLE ROW LEVEL SECURITY;

--> statement-breakpoint
CREATE TABLE "system" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
		sequence name "system_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1
	),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"creator_id" uuid,
	"name" varchar NOT NULL
);

--> statement-breakpoint
ALTER TABLE
	"system" ENABLE ROW LEVEL SECURITY;

--> statement-breakpoint
CREATE TABLE "assign_history" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
		sequence name "assign_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1
	),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"purpose" varchar,
	"instruction" text,
	"assignor_id" uuid DEFAULT gen_random_uuid(),
	"task_id" uuid NOT NULL,
	"assignee_id" uuid
);

--> statement-breakpoint
ALTER TABLE
	"assign_history" ENABLE ROW LEVEL SECURITY;

--> statement-breakpoint
CREATE TABLE "task_goals" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"task_id" uuid NOT NULL,
	"goal_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "task_goals_task_id_goal_id_key" UNIQUE("task_id", "goal_id")
);

--> statement-breakpoint
ALTER TABLE
	"task_goals" ENABLE ROW LEVEL SECURITY;

--> statement-breakpoint
CREATE TABLE "system_users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
		sequence name "system_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1
	),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"system_id" bigint,
	"user_id" uuid
);

--> statement-breakpoint
ALTER TABLE
	"system_users" ENABLE ROW LEVEL SECURITY;

--> statement-breakpoint
CREATE TABLE "task_groups" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"goal_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"order_index" integer DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);

--> statement-breakpoint
ALTER TABLE
	"users"
ADD
	CONSTRAINT "users_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"energy_readings"
ADD
	CONSTRAINT "energy_readings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"tasks"
ADD
	CONSTRAINT "tasks_assignee_id_fkey" FOREIGN KEY ("assignee_id") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"tasks"
ADD
	CONSTRAINT "tasks_assignee_id_fkey1" FOREIGN KEY ("assignee_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"tasks"
ADD
	CONSTRAINT "tasks_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."task_groups"("id") ON DELETE
set
	null ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"tasks"
ADD
	CONSTRAINT "tasks_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."tasks"("id") ON DELETE cascade ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"tasks"
ADD
	CONSTRAINT "tasks_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "public"."tasks"("id") ON DELETE no action ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"system"
ADD
	CONSTRAINT "system_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"assign_history"
ADD
	CONSTRAINT "assign_history_assignee_id_fkey" FOREIGN KEY ("assignee_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"assign_history"
ADD
	CONSTRAINT "assign_history_assignor_id_fkey" FOREIGN KEY ("assignor_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"assign_history"
ADD
	CONSTRAINT "assign_history_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE no action ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"task_goals"
ADD
	CONSTRAINT "task_goals_goal_id_fkey" FOREIGN KEY ("goal_id") REFERENCES "public"."goals"("id") ON DELETE cascade ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"task_goals"
ADD
	CONSTRAINT "task_goals_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE cascade ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"system_users"
ADD
	CONSTRAINT "system_users_system_id_fkey" FOREIGN KEY ("system_id") REFERENCES "public"."system"("id") ON DELETE no action ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"system_users"
ADD
	CONSTRAINT "system_users_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"task_groups"
ADD
	CONSTRAINT "task_groups_goal_id_fkey" FOREIGN KEY ("goal_id") REFERENCES "public"."goals"("id") ON DELETE cascade ON UPDATE no action;

--> statement-breakpoint
ALTER TABLE
	"task_groups"
ADD
	CONSTRAINT "task_groups_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;

--> statement-breakpoint
CREATE INDEX "idx_goals_category" ON "goals" USING btree ("category" text_ops);

--> statement-breakpoint
CREATE INDEX "idx_goals_user_id" ON "goals" USING btree ("user_id" uuid_ops);

--> statement-breakpoint
CREATE INDEX "idx_energy_readings_timestamp" ON "energy_readings" USING btree ("timestamp" timestamptz_ops);

--> statement-breakpoint
CREATE INDEX "idx_energy_readings_user_id" ON "energy_readings" USING btree ("user_id" uuid_ops);

--> statement-breakpoint
CREATE INDEX "idx_tasks_group_id" ON "tasks" USING btree ("group_id" uuid_ops);

--> statement-breakpoint
CREATE INDEX "idx_tasks_parent_id" ON "tasks" USING btree ("parent_id" uuid_ops);

--> statement-breakpoint
CREATE INDEX "idx_tasks_user_id" ON "tasks" USING btree ("user_id" uuid_ops);

--> statement-breakpoint
CREATE INDEX "idx_task_goals_goal_id" ON "task_goals" USING btree ("goal_id" uuid_ops);

--> statement-breakpoint
CREATE INDEX "idx_task_goals_task_id" ON "task_goals" USING btree ("task_id" uuid_ops);

--> statement-breakpoint
CREATE INDEX "idx_task_groups_goal_id" ON "task_groups" USING btree ("goal_id" uuid_ops);

--> statement-breakpoint
CREATE INDEX "idx_task_groups_user_id" ON "task_groups" USING btree ("user_id" uuid_ops);

--> statement-breakpoint
/*
 CREATE POLICY "Users can update own profile" ON "users" AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = id));--> statement-breakpoint
 CREATE POLICY "Users can view own profile" ON "users" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
 CREATE POLICY "Users can delete own goals" ON "goals" AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));--> statement-breakpoint
 CREATE POLICY "Users can insert own goals" ON "goals" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
 CREATE POLICY "Users can update own goals" ON "goals" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
 CREATE POLICY "Users can view own goals" ON "goals" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
 CREATE POLICY "Users can delete own energy readings" ON "energy_readings" AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));--> statement-breakpoint
 CREATE POLICY "Users can insert own energy readings" ON "energy_readings" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
 CREATE POLICY "Users can update own energy readings" ON "energy_readings" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
 CREATE POLICY "Users can view own energy readings" ON "energy_readings" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
 CREATE POLICY "Users can delete own tasks" ON "tasks" AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));--> statement-breakpoint
 CREATE POLICY "Users can insert own tasks" ON "tasks" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
 CREATE POLICY "Users can update own tasks" ON "tasks" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
 CREATE POLICY "Users can view own tasks" ON "tasks" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
 CREATE POLICY "Users can manage their own task-goal relationships" ON "task_goals" AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1
 FROM tasks
 WHERE ((tasks.id = task_goals.task_id) AND (tasks.user_id = auth.uid())))));
 */